model_categories:
  multiclass_classification_base:
    data_types:
      string: TEXT
      categorical: CATEGORICAL
      numeric: NUMERIC

    field_use_types:
      id: ID
      input: INPUT
      target: TARGET

    schemaFields:
      fieldName: field_name
      dataType: data_type
      fieldUseType: field_use_type

    datasets:
      dna_splice_junction:
        fname: dna_splice_junction_schema_cfg.csv
      gesture_phase:
        fname: gesture_phase_schema_cfg.csv
      ipums_census_small:
        fname: ipums_census_small_schema_cfg.csv
      landsat_satellite:
        fname: landsat_satellite_schema_cfg.csv
      page_blocks:
        fname: page_blocks_schema_cfg.csv
      primary_tumor:
        fname: primary_tumor_schema_cfg.csv
      soybean_disease:
        fname: soybean_disease_schema_cfg.csv
      spotify_genre:
        fname: spotify_genre_schema_cfg.csv
      steel_plate_fault:
        fname: steel_plate_fault_schema_cfg.csv
      vehicle_silhouettes:
        fname: vehicle_silhouettes_schema_cfg.csv
